version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=virtuallabs
      - POSTGRES_USER=postgres
      - POSTGRES_DB=virtuallabs
    restart: unless-stopped
  # APP*****************************************
  virtuallabsapp:
    build:
      context: .
      dockerfile: dockerfile
    network_mode: bridge
    container_name: virtuallabsserver
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
